---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: _data/home.yml
  label: Home
- type: directory
  path: _projects
  label: Projects
  create: all
  match: "**/*"
- type: document
  path: _data/default.yml
  label: Defaults
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
